# Generated by Django 4.0.4 on 2022-05-16 23:39

from django.conf import settings
import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(django.contrib.auth.base_user.AbstractBaseUser.__str__), to=settings.AUTH_USER_MODEL),
        ),
    ]
